

IF OBJECT_ID('dbo.Person', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.Person;
END
GO

CREATE TABLE dbo.Person
(
    Id   INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Person PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL
);
GO

;WITH E1(N) AS (
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1
    UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1
),
E2(N) AS (SELECT 1 FROM E1 a, E1 b),             -- 10*10 = 100
E4(N) AS (SELECT 1 FROM E2 a, E2 b),             -- 100*100 = 10,000
Nums AS (
    SELECT TOP (10000) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n FROM E4
)
INSERT INTO dbo.Person(Name)
SELECT
    CHAR(65 + ABS(CHECKSUM(NEWID())) % 26) +
    CHAR(65 + ABS(CHECKSUM(NEWID())) % 26) +
    CHAR(65 + ABS(CHECKSUM(NEWID())) % 26) +
    CHAR(65 + ABS(CHECKSUM(NEWID())) % 26)
FROM Nums;
GO

SELECT COUNT(*) AS InsertedRows FROM dbo.Person;
GO
